
CREATE TABLE users (
    ID INT(10) NOT NULL AUTO_INCREMENT COMMENT 'ID',
    Name VARCHAR(100) NOT NULL COMMENT '姓名',
    Phone VARCHAR(20) NOT NULL COMMENT '手机',
    PasswordHash VARCHAR(255) NOT NULL COMMENT '密码哈希',
    IsAdmin TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否管理员',
    CreatedTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',

    PRIMARY KEY (ID) USING BTREE,
    UNIQUE KEY Phone (Phone),
    INDEX IdxCreatedTime (CreatedTime) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='用户';


CREATE TABLE chats (
    ID INT(10) NOT NULL AUTO_INCREMENT COMMENT 'ID',
    ConversationID VARCHAR(100) NOT NULL COMMENT '大模型的会话ID',
    Title VARCHAR(255) NOT NULL COMMENT '会话标题',
    UserID INT(10) NOT NULL COMMENT 't_users',
    CreatedTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',

    PRIMARY KEY (ID) USING BTREE,
    INDEX IdxUserID (UserID) USING BTREE,
    INDEX IdxCreatedTime (CreatedTime) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='会话';


CREATE TABLE messages (
    ID INT(10) NOT NULL AUTO_INCREMENT COMMENT 'ID',
    ChatID INT(10) NOT NULL COMMENT 't_chats',
    TraceID VARCHAR(100) NOT NULL COMMENT '每次问答的配对',
    Sender VARCHAR(50) NOT NULL COMMENT 'user or robot',
    CreatedTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',

    PRIMARY KEY (ID) USING BTREE,
    INDEX IdxChatID (ChatID) USING BTREE,
    INDEX IdxCreatedTime (CreatedTime) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='消息';


CREATE TABLE contents (
    MessageID INT(10) NOT NULL COMMENT 't_messages',
    Content TEXT NOT NULL COMMENT '消息内容',

    INDEX IdxMessageID (MessageID) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='消息内容';

