
-- 删除表中所有行，并重置自增列
TRUNCATE TABLE table_name;






CREATE TABLE workflow (
    ID INT(10) NOT NULL AUTO_INCREMENT COMMENT 'ID',
    Name VARCHAR(255) NOT NULL COMMENT '流程名称',
    Description TEXT NOT NULL COMMENT '描述',

    PRIMARY KEY (ID) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='流程';


CREATE TABLE node (
    ID INT(10) NOT NULL AUTO_INCREMENT COMMENT 'ID',
    WorkflowID INT(10) NOT NULL COMMENT 't_workflow',
    Name VARCHAR(255) NOT NULL COMMENT '节点名称',
    Order INT NOT NULL COMMENT '节点顺序',
    Func VARCHAR(255) NOT NULL COMMENT '调用的接口',
    Group INT(10) DEFAULT 0 COMMENT '并行调用组',

    PRIMARY KEY (ID) USING BTREE,
    INDEX WorkflowID (WorkflowID) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='节点';


CREATE TABLE record (
    ID INT(10) NOT NULL AUTO_INCREMENT COMMENT 'ID',
    WorkflowID INT(10) NOT NULL COMMENT 't_workflow',
    NodeID INT(10) NOT NULL COMMENT 't_node',
    Status ENUM('pending', 'active', 'done') DEFAULT 'pending' COMMENT '执行状态',
    Func VARCHAR(255) NOT NULL COMMENT '调用的接口',
    Result TEXT COMMENT '执行结果',
    CreatedTime DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedTime DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (ID) USING BTREE,
    INDEX WorkflowID (WorkflowID) USING BTREE,
    INDEX NodeID (NodeID) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='节点执行';

-- ext

CREATE TABLE users (
    ID INT(10) NOT NULL AUTO_INCREMENT COMMENT 'ID',
    Name VARCHAR(100) NOT NULL COMMENT '姓名',
    Gender ENUM('男', '女') NOT NULL COMMENT '性别',
    Birth DATE NOT NULL COMMENT '出生年份',
    Phone VARCHAR(20) NOT NULL COMMENT '手机',
    Address VARCHAR(50) NOT NULL COMMENT '地区',
    Comment VARCHAR(255) NULL DEFAULT NULL COMMENT '备注',
    CreatedTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (ID) USING BTREE,
    UNIQUE KEY Phone (Phone),
    INDEX CreatedTime (CreatedTime) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='客户';


CREATE TABLE user_sources (
    ID INT(10) NOT NULL AUTO_INCREMENT COMMENT 'ID',
    Name VARCHAR(100) NOT NULL COMMENT '来源',

    PRIMARY KEY (ID) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='客户来源';


CREATE TABLE user_source_relations (
    ID INT(10) NOT NULL AUTO_INCREMENT COMMENT 'ID',
    UserId INT(10) NOT NULL COMMENT 't_users',
    SourceId INT(10) NOT NULL COMMENT 't_user_sources',

    PRIMARY KEY (ID) USING BTREE,
    INDEX UserId (UserId) USING BTREE,
    INDEX SourceId (SourceId) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='客户-来源关系';


CREATE TABLE jobs (
    ID INT(10) NOT NULL AUTO_INCREMENT COMMENT 'ID',
    Name VARCHAR(100) NOT NULL COMMENT '职业',

    PRIMARY KEY (ID) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='职业';


CREATE TABLE goods (
    ID INT(10) NOT NULL AUTO_INCREMENT COMMENT 'ID',
    Name VARCHAR(100) NOT NULL COMMENT '商品',
    Descr VARCHAR(255) NOT NULL COMMENT '商品描述',
    Price DOUBLE(10, 2) NOT NULL COMMENT '销售价格',
    Num INT(11) NOT NULL COMMENT '数量',
    Unit VARCHAR(255) NOT NULL COMMENT '商品规格',
    Pack VARCHAR(255) NOT NULL COMMENT '包装单位',
    Img VARCHAR(255) NOT NULL COMMENT '商品图片',
    ProductNum VARCHAR(255) NOT NULL  COMMENT '生产批号',
    ApproveNum VARCHAR(255) NOT NULL  COMMENT '批准文号',
    Status ENUM('可用', '禁用') DEFAULT '可用' COMMENT '状态',

    PRIMARY KEY (ID) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='职业';


CREATE TABLE sales (
    ID INT(10) NOT NULL AUTO_INCREMENT COMMENT 'ID',
    Name VARCHAR(100) NOT NULL COMMENT '购买标识',
    PayType VARCHAR(100) NOT NULL COMMENT '支付类型',
    CreatedTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (ID) USING BTREE,
    INDEX GoodsId (GoodsId) USING BTREE,
    INDEX CreatedTime (CreatedTime) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='购买单';


CREATE TABLE sale_goods (
    ID INT(10) NOT NULL AUTO_INCREMENT COMMENT 'ID',
    SaleId INT(10) NOT NULL COMMENT 't_sales',
    GoodsId INT(10) NOT NULL COMMENT 't_goods',
    Price DOUBLE NOT NULL COMMENT '销售单价',
    Num INT(11) NOT NULL COMMENT '销售数量',
    Unit VARCHAR(255) NOT NULL COMMENT '商品规格',
    Total DOUBLE(10, 2) NOT NULL COMMENT '销售总价',
    Comment VARCHAR(255) NOT NULL COMMENT '备注',

    PRIMARY KEY (ID) USING BTREE,
    INDEX SaleId (SaleId) USING BTREE,
    INDEX GoodsId (GoodsId) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='商品-购买单关系';


CREATE TABLE user_sales (
    ID INT(10) NOT NULL AUTO_INCREMENT COMMENT 'ID',
    UserId INT(10) NOT NULL COMMENT 't_users',
    SaleId INT(10) NOT NULL COMMENT 't_sales',

    PRIMARY KEY (ID) USING BTREE,
    INDEX UserId (UserId) USING BTREE,
    INDEX SaleId (SaleId) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='客户-购买单关系';







